/**
 * MirraSync Model Registry
 * Central source of truth for all supported AI models.
 * Each model has metadata for UI display, API routing, and capability flags.
 */

const MODEL_REGISTRY = [
  // ─── GITHUB MODELS ──────────────────────────────────────────────
  {
    id: 'github-gpt-4o',
    displayName: 'GPT-4o',
    provider: 'github_models',
    providerLabel: 'GitHub Models',
    modelId: 'gpt-4o',
    supportsVision: true,
    supportsFiles: true,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'OpenAI\'s latest GPT-4.1 model, available via GitHub Models',
    colorAccent: '#10a37f',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'GITHUB_MODELS_BASE_URL',
    apiKeyEnv: 'GITHUB_MODELS_API_KEY',
    category: 'frontier',
  },
  {
    id: 'github-grok-3',
    displayName: 'Grok 3',
    provider: 'github_models',
    providerLabel: 'GitHub Models',
    modelId: 'grok-3',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'xAI\'s flagship model with strong reasoning capabilities',
    colorAccent: '#1d9bf0',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'GITHUB_MODELS_BASE_URL',
    apiKeyEnv: 'GITHUB_MODELS_API_KEY',
    category: 'frontier',
  },
  {
    id: 'github-deepseek-r1',
    displayName: 'DeepSeek R1',
    provider: 'github_models',
    providerLabel: 'GitHub Models',
    modelId: 'DeepSeek-R1',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Best open-source reasoning model, chain-of-thought specialist',
    colorAccent: '#4a90d9',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'GITHUB_MODELS_BASE_URL',
    apiKeyEnv: 'GITHUB_MODELS_API_KEY',
    category: 'reasoning',
  },

  // ─── GOOGLE AI STUDIO ───────────────────────────────────────────
  {
    id: 'google-gemini-25-flash',
    displayName: 'Gemini 2.5 Flash',
    provider: 'google_ai',
    providerLabel: 'Google AI Studio',
    modelId: 'gemini-2.5-flash',
    supportsVision: true,
    supportsFiles: true,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Best free reasoning model with vision and multimodal support',
    colorAccent: '#4285f4',
    adapterType: 'google_ai',
    baseUrlEnv: 'GOOGLE_AI_BASE_URL',
    apiKeyEnv: 'GOOGLE_AI_API_KEY',
    category: 'reasoning',
  },
  {
    id: 'google-gemini-3-flash',
    displayName: 'Gemini 2.0 Flash',
    provider: 'google_ai',
    providerLabel: 'Google AI Studio',
    modelId: 'gemini-2.0-flash',
    supportsVision: true,
    supportsFiles: true,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Fast multimodal model — great for everyday tasks',
    colorAccent: '#4285f4',
    adapterType: 'google_ai',
    baseUrlEnv: 'GOOGLE_AI_BASE_URL',
    apiKeyEnv: 'GOOGLE_AI_API_KEY',
    category: 'fast',
  },
  {
    id: 'google-gemini-31-flash-lite',
    displayName: 'Gemini 2.0 Flash Lite',
    provider: 'google_ai',
    providerLabel: 'Google AI Studio',
    modelId: 'gemini-2.0-flash-lite-001',
    supportsVision: true,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Most cost-efficient — lightweight and fast',
    colorAccent: '#4285f4',
    adapterType: 'google_ai',
    baseUrlEnv: 'GOOGLE_AI_BASE_URL',
    apiKeyEnv: 'GOOGLE_AI_API_KEY',
    category: 'fast',
  },

  // ─── GROQ ───────────────────────────────────────────────────────
  {
    id: 'groq-kimi-k2',
    displayName: 'Kimi K2',
    provider: 'groq',
    providerLabel: 'Groq',
    modelId: 'moonshotai/kimi-k2-instruct',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Exclusive top-tier model — exceptional reasoning and instruction following',
    colorAccent: '#f55036',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'GROQ_BASE_URL',
    apiKeyEnv: 'GROQ_API_KEY',
    category: 'reasoning',
  },
  {
    id: 'groq-llama4-scout',
    displayName: 'Llama 4 Scout',
    provider: 'groq',
    providerLabel: 'Groq',
    modelId: 'meta-llama/llama-4-scout-17b-16e-instruct',
    supportsVision: true,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Meta\'s best Llama 4 model with vision support, ultra-fast on Groq',
    colorAccent: '#f55036',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'GROQ_BASE_URL',
    apiKeyEnv: 'GROQ_API_KEY',
    category: 'fast',
  },
  {
    id: 'groq-qwen3-32b',
    displayName: 'Qwen3 32B',
    provider: 'groq',
    providerLabel: 'Groq',
    modelId: 'qwen/qwen3-32b',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Only 32B Qwen model available here — strong coding and reasoning',
    colorAccent: '#f55036',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'GROQ_BASE_URL',
    apiKeyEnv: 'GROQ_API_KEY',
    category: 'coding',
  },

  // ─── CEREBRAS ───────────────────────────────────────────────────
  {
    id: 'cerebras-gpt-oss-120b',
    displayName: 'GPT-OSS 120B',
    provider: 'cerebras',
    providerLabel: 'Cerebras',
    modelId: 'gpt-oss-120b',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'World\'s fastest inference — 120B parameter model at unbelievable speed',
    colorAccent: '#ff6b35',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'CEREBRAS_BASE_URL',
    apiKeyEnv: 'CEREBRAS_API_KEY',
    category: 'fast',
  },
  {
    id: 'cerebras-llama31-8b',
    displayName: 'Llama 3.1 8B',
    provider: 'cerebras',
    providerLabel: 'Cerebras',
    modelId: 'llama3.1-8b',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Instant responses — smallest Llama with Cerebras ultra-fast chips',
    colorAccent: '#ff6b35',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'CEREBRAS_BASE_URL',
    apiKeyEnv: 'CEREBRAS_API_KEY',
    category: 'fast',
  },

  // ─── COHERE ─────────────────────────────────────────────────────
  {
    id: 'cohere-command-a-reasoning',
    displayName: 'Command A Reasoning',
    provider: 'cohere',
    providerLabel: 'Cohere',
    modelId: 'command-a-reasoning-08-2025',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Cohere\'s exclusive reasoning model — August 2025 flagship',
    colorAccent: '#39594d',
    adapterType: 'cohere',
    baseUrlEnv: 'COHERE_BASE_URL',
    apiKeyEnv: 'COHERE_API_KEY',
    category: 'reasoning',
  },
  {
    id: 'cohere-command-a-vision',
    displayName: 'Command A Vision',
    provider: 'cohere',
    providerLabel: 'Cohere',
    modelId: 'command-a-vision-07-2025',
    supportsVision: true,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Cohere\'s exclusive vision model — image understanding specialist',
    colorAccent: '#39594d',
    adapterType: 'cohere',
    baseUrlEnv: 'COHERE_BASE_URL',
    apiKeyEnv: 'COHERE_API_KEY',
    category: 'vision',
  },
  {
    id: 'cohere-aya-expanse-32b',
    displayName: 'Aya Expanse 32B',
    provider: 'cohere',
    providerLabel: 'Cohere',
    modelId: 'c4ai-aya-expanse-32b',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Exclusive multilingual model supporting 23+ languages',
    colorAccent: '#39594d',
    adapterType: 'cohere',
    baseUrlEnv: 'COHERE_BASE_URL',
    apiKeyEnv: 'COHERE_API_KEY',
    category: 'multilingual',
  },

  // ─── MISTRAL ────────────────────────────────────────────────────
  {
    id: 'mistral-small-31',
    displayName: 'Mistral Small 3.1',
    provider: 'mistral',
    providerLabel: 'Mistral',
    modelId: 'mistral-small-2503',
    supportsVision: true,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Best open-source Mistral model with vision capabilities',
    colorAccent: '#ff7000',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'MISTRAL_BASE_URL',
    apiKeyEnv: 'MISTRAL_API_KEY',
    category: 'frontier',
  },
  {
    id: 'mistral-large',
    displayName: 'Mistral Large',
    provider: 'mistral',
    providerLabel: 'Mistral',
    modelId: 'mistral-large-latest',
    supportsVision: true,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Exclusive proprietary Mistral flagship — strongest reasoning',
    colorAccent: '#ff7000',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'MISTRAL_BASE_URL',
    apiKeyEnv: 'MISTRAL_API_KEY',
    category: 'frontier',
  },
  {
    id: 'mistral-codestral',
    displayName: 'Codestral',
    provider: 'mistral',
    providerLabel: 'Mistral',
    modelId: 'codestral-latest',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Dedicated code model — fills completions, fixes bugs, explains code',
    colorAccent: '#ff7000',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'MISTRAL_BASE_URL',
    apiKeyEnv: 'MISTRAL_API_KEY',
    category: 'coding',
  },

  // ─── OPENROUTER ─────────────────────────────────────────────────
  {
    id: 'openrouter-hermes-405b',
    displayName: 'Hermes 3 405B',
    provider: 'openrouter',
    providerLabel: 'OpenRouter',
    modelId: 'nousresearch/hermes-3-llama-3.1-405b',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Exclusive 405B Llama fine-tune — Nous Research\'s best model',
    colorAccent: '#7c3aed',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'OPENROUTER_BASE_URL',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    extraHeaders: { 'HTTP-Referer': process.env.FRONTEND_URL, 'X-Title': 'MirraSync' },
    category: 'frontier',
  },
  {
    id: 'openrouter-step-35-flash',
    displayName: 'Step 3.5 Flash',
    provider: 'openrouter',
    providerLabel: 'OpenRouter',
    modelId: 'stepfun/step-3.5-flash',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Exclusive StepFun provider — unique Chinese AI research model',
    colorAccent: '#7c3aed',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'OPENROUTER_BASE_URL',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    extraHeaders: { 'HTTP-Referer': process.env.FRONTEND_URL, 'X-Title': 'MirraSync' },
    category: 'frontier',
  },
  {
    id: 'openrouter-qwen3-coder',
    displayName: 'Qwen3 Coder',
    provider: 'openrouter',
    providerLabel: 'OpenRouter',
    modelId: 'qwen/qwen3-coder',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Qwen\'s dedicated coding specialist with reasoning capabilities',
    colorAccent: '#7c3aed',
    adapterType: 'openai_compatible',
    baseUrlEnv: 'OPENROUTER_BASE_URL',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    extraHeaders: { 'HTTP-Referer': process.env.FRONTEND_URL, 'X-Title': 'MirraSync' },
    category: 'coding',
  },

  // ─── CLOUDFLARE WORKERS AI ──────────────────────────────────────
  {
    id: 'cf-ibm-granite',
    displayName: 'IBM Granite 4.0',
    provider: 'cloudflare',
    providerLabel: 'Cloudflare AI',
    modelId: '@cf/ibm-granite/granite-4.0-h-micro',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'IBM enterprise model — optimized for agentic tasks',
    colorAccent: '#f4a100',
    adapterType: 'cloudflare',
    baseUrlEnv: 'CLOUDFLARE_BASE_URL',
    apiKeyEnv: 'CLOUDFLARE_API_KEY',
    category: 'frontier',
  },
  {
    id: 'cf-qwen-qwq-32b',
    displayName: 'Qwen QwQ 32B',
    provider: 'cloudflare',
    providerLabel: 'Cloudflare AI',
    modelId: '@cf/qwen/qwq-32b',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: true,
    isFree: true,
    requiresUserKey: false,
    description: 'Qwen\'s reasoning specialist — deliberate, step-by-step thinking',
    colorAccent: '#f4a100',
    adapterType: 'cloudflare',
    baseUrlEnv: 'CLOUDFLARE_BASE_URL',
    apiKeyEnv: 'CLOUDFLARE_API_KEY',
    category: 'reasoning',
  },
  {
    id: 'cf-glm-47-flash',
    displayName: 'GLM 4.7 Flash',
    provider: 'cloudflare',
    providerLabel: 'Cloudflare AI',
    modelId: '@cf/zai-org/glm-4.7-flash',
    supportsVision: false,
    supportsFiles: false,
    supportsReasoning: false,
    isFree: true,
    requiresUserKey: false,
    description: 'Fast multilingual model — 131K context, 100+ languages',
    colorAccent: '#f4a100',
    adapterType: 'cloudflare',
    baseUrlEnv: 'CLOUDFLARE_BASE_URL',
    apiKeyEnv: 'CLOUDFLARE_API_KEY',
    category: 'multilingual',
  },
];

function getModelById(id) {
  return MODEL_REGISTRY.find(m => m.id === id) || null;
}

function getModelsByProvider(provider) {
  return MODEL_REGISTRY.filter(m => m.provider === provider);
}

function getFreeModels() {
  return MODEL_REGISTRY.filter(m => m.isFree && !m.requiresUserKey);
}

module.exports = { MODEL_REGISTRY, getModelById, getModelsByProvider, getFreeModels };
